#!/usr/bin/env bash

cd "${FILES_DIR}"
ls -la .

REPOSITORY_URL="${PULP_BASE_URL}${PULP_API_ROOT}pypi/${PULP_DOMAIN}/${PULP_REPOSITORY}/"
CLIENT_CERT_FILE="/tmp/client-cert.pem"
# twine requires both cert/key in a single file
cat /etc/pulp-secret/cert /etc/pulp-secret/key > "${CLIENT_CERT_FILE}"
chmod 600 "${CLIENT_CERT_FILE}"

# Check if we have attestation files
shopt -s nullglob
attestation_files=(*.attestation)

if [ ${#attestation_files[@]} -gt 0 ]; then
    echo "Uploading packages with attestations..."
    twine upload --repository-url "${REPOSITORY_URL}" --client-cert "${CLIENT_CERT_FILE}" --attestations *.whl *.tar.gz *.attestation
else
    echo "Uploading packages..."
    twine upload --repository-url "${REPOSITORY_URL}" --client-cert "${CLIENT_CERT_FILE}" *.whl *.tar.gz
fi

rm -f "${CLIENT_CERT_FILE}"

echo ""
echo "Upload complete!"
echo "Index URL: https://console.redhat.com/api/pulp-content/public-calunga/mypypi/simple/"
