# This Containerfile is inspired by the Containerfile used by Hermeto:
#   https://github.com/hermetoproject/hermeto/blob/main/Dockerfile

# Cosign from Red Hat Trusted Artifact Signer.
FROM registry.redhat.io/rhtas/cosign-rhel9:1.4.3-1785391843@sha256:c41399a432868f51897c762b2ece554848b06ba40c1f3248dcf100dc2e3d503d AS cosign

# ORAS client from Konflux's UBI-based image (no registry.redhat.io/oras equivalent;
# same source release-service-utils uses).
FROM quay.io/konflux-ci/oras:latest@sha256:6cea0b9e142c2e18429f5cd30d716715d932047cbf1631334c5c31f7e47c3a19 AS oras

FROM registry.access.redhat.com/ubi10/ubi:latest as ubi

########################
# PREPARE OUR BASE IMAGE
########################
FROM ubi as base
RUN dnf -y install \
    --setopt install_weak_deps=0 \
    --nodocs \
    python3 \
    jq \
    curl \
    findutils \
    && dnf clean all

###############
# BUILD/INSTALL
###############
FROM base as builder
WORKDIR /src

COPY requirements.txt .
RUN python3 -m venv /venv && \
    /venv/bin/pip install -r requirements.txt --no-deps --no-cache-dir --require-hashes

##########################
# ASSEMBLE THE FINAL IMAGE
##########################
FROM base
LABEL maintainer="Red Hat"

COPY --from=builder /venv /venv
COPY --from=cosign /usr/local/bin/cosign /usr/local/bin/cosign
COPY --from=oras /usr/bin/oras /usr/local/bin/oras
COPY --from=oras /usr/local/bin/retry /usr/local/bin/retry

COPY scripts/* /usr/local/bin/

RUN ln -s /venv/bin/twine /usr/local/bin/twine

# Force the stdout and stderr streams to be unbuffered.
# https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED
ENV PYTHONUNBUFFERED=1
