# This Containerfile is inspired by the Containerfile used by Hermeto:
#   https://github.com/hermetoproject/hermeto/blob/main/Dockerfile

# Cosign from Red Hat Trusted Artifact Signer.
FROM registry.redhat.io/rhtas/cosign-rhel9:1.3.6@sha256:ff6a2a11b8c1dff47cb115cfa3ba5709bff5f1cf485bdaecff47f1a37cad2405 AS cosign

# ORAS client from Konflux's UBI-based image (no registry.redhat.io/oras equivalent;
# same source release-service-utils uses).
FROM quay.io/konflux-ci/oras:latest@sha256:b38167deed2c10441fc9b810055ab1763a4dfb14b1a2144b6b37a9fa7d806a2a AS oras

FROM registry.access.redhat.com/ubi10/ubi:latest as ubi

########################
# PREPARE OUR BASE IMAGE
########################
FROM ubi as base
RUN dnf -y install \
    --setopt install_weak_deps=0 \
    --nodocs \
    python3 \
    jq \
    curl \
    findutils \
    && dnf clean all

###############
# BUILD/INSTALL
###############
FROM base as builder
WORKDIR /src

COPY requirements.txt .
RUN python3 -m venv /venv && \
    /venv/bin/pip install -r requirements.txt --no-deps --no-cache-dir --require-hashes

##########################
# ASSEMBLE THE FINAL IMAGE
##########################
FROM base
LABEL maintainer="Red Hat"

COPY --from=builder /venv /venv
COPY --from=cosign /usr/local/bin/cosign /usr/local/bin/cosign
COPY --from=oras /usr/bin/oras /usr/local/bin/oras
COPY --from=oras /usr/local/bin/retry /usr/local/bin/retry

COPY scripts/* /usr/local/bin/

RUN ln -s /venv/bin/twine /usr/local/bin/twine

# Force the stdout and stderr streams to be unbuffered.
# https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED
ENV PYTHONUNBUFFERED=1
