apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/calungaproject/plumbing?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" && ( "tasks/push-py-pulp.yaml".pathChanged() || ".tekton/task-push-py-pulp-push.yaml".pathChanged() || ".tekton/bundle-build-pipeline.yaml".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: calunga-v2
    appstudio.openshift.io/component: task-push-py-pulp
    pipelines.appstudio.openshift.io/type: build
  name: task-push-py-pulp-on-push
  namespace: calunga-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/calunga-tenant/task-push-py-pulp:{{revision}}
    - name: dockerfile
      value: Dockerfile
    - name: path-context
      value: tasks/push-py-pulp.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-task-push-py-pulp
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
  pipelineRef:
    name: bundle-build
status: {}
