apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/calungaproject/plumbing?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: calunga-v2
    appstudio.openshift.io/component: task-get-config
    pipelines.appstudio.openshift.io/type: build
  name: task-get-config-on-pull-request
  namespace: calunga-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/calunga-tenant/task-get-config:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: dockerfile
      value: Dockerfile
    - name: path-context
      value: tasks/get-config.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-task-get-config
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
  pipelineRef:
    name: bundle-build
status: {}
