apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/calungaproject/plumbing?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "main" && ( "tasks/build-python-wheels-oci-ta.yaml".pathChanged() || ".tekton/task-build-python-wheels-pull-request.yaml".pathChanged() || ".tekton/bundle-build-pipeline.yaml".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: calunga-v2
    appstudio.openshift.io/component: task-build-python-wheels
    pipelines.appstudio.openshift.io/type: build
  name: task-build-python-wheels-on-pull-request
  namespace: calunga-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/calunga-tenant/task-build-python-wheels:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: dockerfile
      value: Dockerfile
    - name: path-context
      value: tasks/build-python-wheels-oci-ta.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-task-build-python-wheels
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
  pipelineRef:
    name: bundle-build
status: {}
